//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcesadorBib
{
    using System;
    using System.Collections.Generic;
    
    public partial class BibEntry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BibEntry()
        {
            this.BibEntryAuthor = new HashSet<BibEntryAuthor>();
            this.BibEntryEvent = new HashSet<BibEntryEvent>();
            this.BibEntryReference = new HashSet<BibEntryReference>();
            this.BibEntryReference1 = new HashSet<BibEntryReference>();
            this.BibEntrySubject = new HashSet<BibEntrySubject>();
            this.EntryTag = new HashSet<EntryTag>();
        }
    
        public System.Guid EntryID { get; set; }
        public string EntryType { get; set; }
        public string EntryKey { get; set; }
        public string @abstract { get; set; }
        public string annote { get; set; }
        public string booktitle { get; set; }
        public string ISBN { get; set; }
        public string publisher { get; set; }
        public string title { get; set; }
        public string url { get; set; }
        public string year { get; set; }
        public string doi { get; set; }
        public string ISSN { get; set; }
        public string volume { get; set; }
        public string author { get; set; }
        public string keywords { get; set; }
        public string pages { get; set; }
        public string month { get; set; }
        public string journal { get; set; }
        public string number { get; set; }
        public string address { get; set; }
        public string editor { get; set; }
        public string archivePrefix { get; set; }
        public string arxivId { get; set; }
        public string eprint { get; set; }
        public string series { get; set; }
        public string db { get; set; }
        public string edition { get; set; }
        public string day { get; set; }
        public string note { get; set; }
        public Nullable<int> EntryStatus { get; set; }
        public string jsondata { get; set; }
        public Nullable<System.DateTime> indexed { get; set; }
        public Nullable<System.DateTime> publishedprint { get; set; }
        public string articletype { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<int> score { get; set; }
        public Nullable<System.DateTime> issued { get; set; }
        public Nullable<System.DateTime> published { get; set; }
        public Nullable<int> isreferencedbycount { get; set; }
        public string cISSN { get; set; }
        public string cISBN { get; set; }
        public string containertitle { get; set; }
        public string bibtex { get; set; }
        public string articleno { get; set; }
        public string numpages { get; set; }
        public string location { get; set; }
        public string issue_date { get; set; }
        public string exclusion_json { get; set; }
        public Nullable<int> proximity { get; set; }
        public string rq1_json { get; set; }
        public string rq2_json { get; set; }
        public string rq3_json { get; set; }
        public string rq4_json { get; set; }
        public string classification { get; set; }
        public string rq1_model_families_json { get; set; }
        public string rq1_prediction_targets_json { get; set; }
        public string rq1_prediction_timing_json { get; set; }
        public string rq1_input_modalities_json { get; set; }
        public string rq1_study_design { get; set; }
        public string rq1_setting_scope { get; set; }
        public string rq1_setting_country { get; set; }
        public Nullable<int> rq1_sample_size_n { get; set; }
        public string rq2_reported_metrics_json { get; set; }
        public Nullable<decimal> rq2_auc { get; set; }
        public Nullable<decimal> rq2_auc_ci_low { get; set; }
        public Nullable<decimal> rq2_auc_ci_high { get; set; }
        public Nullable<decimal> rq2_accuracy { get; set; }
        public Nullable<decimal> rq2_sensitivity { get; set; }
        public Nullable<decimal> rq2_specificity { get; set; }
        public Nullable<decimal> rq2_ppv { get; set; }
        public Nullable<decimal> rq2_npv { get; set; }
        public Nullable<decimal> rq2_f1 { get; set; }
        public Nullable<decimal> rq2_brier { get; set; }
        public Nullable<decimal> rq2_hl_p { get; set; }
        public string rq2_internal_validation { get; set; }
        public Nullable<bool> rq2_comparator_present { get; set; }
        public string rq2_comparator_type { get; set; }
        public Nullable<bool> rq3_repository_mentioned { get; set; }
        public string rq3_repository_name { get; set; }
        public string rq3_access_type { get; set; }
        public string rq3_data_types_json { get; set; }
        public string rq4_feature_groups_json { get; set; }
        public string rq4_top_predictors { get; set; }
        public string rq5_real_world_design { get; set; }
        public Nullable<decimal> rq5_real_world_auc { get; set; }
        public Nullable<decimal> rq5_real_world_auc_ci_low { get; set; }
        public Nullable<decimal> rq5_real_world_auc_ci_high { get; set; }
        public string rq5_bias_risk_signals_json { get; set; }
        public Nullable<bool> rq6_external_validation { get; set; }
        public string rq6_external_validation_site { get; set; }
        public string rq6_techniques_compared_json { get; set; }
        public string rq6_statistical_comparison_json { get; set; }
        public Nullable<bool> rq7_explainability_used { get; set; }
        public string rq7_explainability_methods_json { get; set; }
        public string rq7_clinical_use_of_explanations { get; set; }
        public string coding_notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BibEntryAuthor> BibEntryAuthor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BibEntryEvent> BibEntryEvent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BibEntryReference> BibEntryReference { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BibEntryReference> BibEntryReference1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BibEntrySubject> BibEntrySubject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntryTag> EntryTag { get; set; }
    }
}
