//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcesadorBib
{
    using System;
    using System.Collections.Generic;
    
    public partial class BibEntry_Doi_VTA
    {
        public System.Guid EntryID { get; set; }
        public string doi { get; set; }
    }
}
