//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcesadorBib
{
    using System;
    using System.Collections.Generic;
    
    public partial class BibEntryAuthor
    {
        public System.Guid BibEntryAuthorID { get; set; }
        public Nullable<System.Guid> AuthorID { get; set; }
        public Nullable<System.Guid> EntryID { get; set; }
        public string sequence { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual BibEntry BibEntry { get; set; }
    }
}
