//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcesadorBib
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DOC_TmpEntities : DbContext
    {
        public DOC_TmpEntities()
            : base("name=DOC_TmpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EntryTag> EntryTag { get; set; }
        public virtual DbSet<taggroup> taggroup { get; set; }
        public virtual DbSet<Author> Author { get; set; }
        public virtual DbSet<BibEntryAuthor> BibEntryAuthor { get; set; }
        public virtual DbSet<BibEntryEvent> BibEntryEvent { get; set; }
        public virtual DbSet<BibEntryReference> BibEntryReference { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<BibEntrySubject> BibEntrySubject { get; set; }
        public virtual DbSet<Subject> Subject { get; set; }
        public virtual DbSet<BibEntry> BibEntry { get; set; }
        public virtual DbSet<BibEntry_Doi_VTA> BibEntry_Doi_VTA { get; set; }
    
        public virtual ObjectResult<Doc_Tags_Result> Doc_Tags()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Doc_Tags_Result>("Doc_Tags");
        }
    
        public virtual int BibEntry_Duplicados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BibEntry_Duplicados");
        }
    }
}
