//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcesadorBib
{
    using System;
    using System.Collections.Generic;
    
    public partial class taggroup
    {
        public string tag { get; set; }
        public string taggroup1 { get; set; }
    }
}
